version: 2

group_defaults:
  approve_by_comment:
    approve_regex: ^(Approved|:\+1:)
    enabled: true
    reject_regex: ^(Rejected|:-1:)
  reset_on_push:
    enabled: false

groups:
  code-review:
    required: 1
    users: all
    approve_by_comment:
      approve_regex: ^(Approved|:\+1:)\s*Code
      enabled: true

  product-manager:
    required: 1
    teams:
      - product-manager

  architect:
    required: 1
    teams:
      - architect

  test-engineer:
    required: 1
    teams:
      - test-engineer
